export const GET_GUARDIANS_DATA_REQUEST = "GET_GUARDIANS_DATA_REQUEST"
export const GET_GUARDIANS_DATA_SUCCESSFULL = "GET_GUARDIANS_DATA_SUCCESSFULL"
export const GET_GUARDIANS_DATA_FAILURE = "GET_GUARDIANS_DATA_FAILURE"

export const PATCH_USER_DATA_REQUEST = "PATCH_USER_DATA_REQUEST";
export const PATCH_USER_DATA_SUCCESS = "PATCH_USER_DATA_SUCCESS";
export const PATCH_USER_DATA_FAILURE = "PATCH_USER_DATA_FAILURE";

export const POST_USER_DATA_REQUEST = "POST_USER_DATA_REQUEST";
export const POST_USER_DATA_SUCCESSFUL = "POST_USER_DATA_SUCCESSFUL";
export const POST_USER_DATA_FAILURE = "POST_USER_DATA_FAILURE";

